apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: alekseychii/flask-app:latest
        name: app
        ports:
        - containerPort: 5000
          name: app
        volumeMounts:
        - name: secrets-for-db
          mountPath: /app
      volumes:
      - name: secrets-for-db
        secret:
          secretName: db-password
